package medicina;

public enum Tipo_medico {
	FAMILIAR, INTERNISTA, PEDIATRA, GERIATRA, PSIQUIATRA, PSICOLOGO,CARDIOLOGO, DERMATOLOGO, 
	ENDOCRINOLOGO, GASTROENTEROLOGO, NEUMOLOGO, NEUROLOGO, ONCOLOGO, REUMATOLOGO, ALERGOLOGO, NEFROLOGO,
	CIRUJANO_GENERAL, CIRUJANO_ORTOPEDICO, NEUROCIRUJANO, CIRUJANO_CARDIOVASCULAR, CIRUJANO_PLASTICO,
	OFALMOLOGO, OTORRINOLARINGOLOGO, UROLOGO, GINECOLOGO, RADIOLOGO 
	
}
